### ISSUE TITLE
CasFinder specificity filter is not working

### ISSUE THREAD

**Issue by Nureke1286** [BenLangmead/bowtie#10]
I run a CasFinder with installation test file, and my results are not same with provided test results. The program executes normally (no errors in log file), however it shows all target seq. without sorting out off targets and target_threshold_rejection_score is always Inf 1. (running it on windows). so according to test file i have to receive 146 possible cas targets and among them 39 pass specificity conditions. But in my case all 146 pass specificity condition. How can i solve this issue?

**Comment by val-antonescu** [comment]
I am not sure this can be classified as a bowtie issue. Have you tried contacting the CasFinder authors regarding this? 
I will leave this open for a while just to be make sure this is not bowtie related somehow.

Val
