### ISSUE TITLE
Missing newlines in --max and --un output files

### ISSUE THREAD

**Issue by ferayd** [BenLangmead/bowtie#100]
Hello,

I am running Bowtie 1.2.3 on a raw input file, and I am using the "--max" and "--un" parameters.

My Bowtie command is like this:
bowtie --all -v 0 -m 50 <bowtie_index> -r <read_file> <output_file> --max <max_file> --un <unmapped_file>

The <max_file> and <unmapped_file> created by Bowtie don't have any newlines. Everything is on the same line.

Could you take a look at this issue?

Thanks

**Comment by mschilli87** [comment]
@ferayd: Which operating system are you on? Can you check if there is any non-visible line separator using `od -c`?

**Comment by ferayd** [comment]
@mschilli87: I am on Linux (CentOS 6.6). There are no non-visible line separators. I had already checked. :)

Thanks

**Comment by mschilli87** [comment]
How did you install bowtie? On my CentOS 7 box, `yum install bowtie` has nothing for me. Also, can you provide a minimal (fake) dataset (one short  contig and three reads or so) incl. exact command to reproduce this?

**Comment by ferayd** [comment]
@mschilli87, I downloaded the Linux archive from the bowtie homepage (http://bowtie-bio.sourceforge.net/index.shtml) and extracted it.

With the files I attached, you can reproduce the problem like this:
```
bowtie-build contigs.fa.txt contigs_index
bowtie --all -v 0 -m 3 contigs_index -r reads.txt output.txt --max max.txt --un unmapped.txt
```
max.txt and unmapped.txt don't have any newlines.

[contigs.fa.txt](https://github.com/BenLangmead/bowtie/files/4001209/contigs.fa.txt)
[reads.txt](https://github.com/BenLangmead/bowtie/files/4001210/reads.txt)

**Comment by pbaldrich** [comment]
Hi all,
I have the same issue!! It would be great if we could get it fixed!!

Thanks!

**Comment by ch4rr0** [comment]
@ferayd -- I made a few that seem have resolved the issue. Using the sample files that you provided can you confirm that the below output is what you expect?

```
$ ./bowtie --all -v 0 -m3 contigs_index -r reads.txt output.txt --max max.txt --un unmapped.txt
# reads processed: 3
# reads with at least one reported alignment: 1 (33.33%)
# reads that failed to align: 2 (66.67%)
# reads with alignments suppressed due to -m: 2 (66.67%)
Reported 1 alignments
$ cat max.txt
AT
CG
$ cat unmapped.txt
GAGAGA
TCTCTC
```

**Comment by ferayd** [comment]
Hi @ch4rr0, the problem still exists. But where is the new code? There are no new commits in this repository.

**Comment by ch4rr0** [comment]
I pushed the changes to the `bug_fixes` branch.

**Comment by ferayd** [comment]
Hi @ch4rr0, thanks, the problem is fixed!
Are you going to release a new Bowtie version soon? :)

**Comment by ferayd** [comment]
Hi @ch4rr0, are you going to release a new Bowtie version soon?

**Comment by ch4rr0** [comment]
Hello @ferayd,

I am planning on having a new version released by the end of next week.

**Comment by ch4rr0** [comment]
@ferayd -- Were you having this issue only while using sequences, `-r`? I may need to revisit this change if that is the case.

**Comment by ferayd** [comment]
Hi @ch4rr0, I only tested with the "-r" parameter. That is the only type of input file I have.

**Comment by ch4rr0** [comment]
I've found and fixed the true cause of the issue. Will have a commit pushed sometime today.

**Comment by ferayd** [comment]
Hi @ch4rr0, I tested the bug_fixes branch. The problem still exists there. I am using Linux, not Windows.

**Comment by ch4rr0** [comment]
> Hi @ch4rr0, I tested the bug_fixes branch. The problem still exists there. I am using Linux, not Windows.

@ferayd -- The fix was overwritten by some changes I made recently. I have re-instated them:

``` shell
./bowtie --all -v 0 -m3 /tmp/out -r reads.txt output.txt --max max.txt --un unmapped.txt
# reads processed: 5
# reads with at least one alignment: 3 (60.00%)
# reads that failed to align: 2 (40.00%)
# reads with alignments suppressed due to -m: 2 (40.00%)
Reported 1 alignments
$ cat output.txt
2	+	contig1	37	AAAA	IIII	0
$ cat max.txt
AT
CG
$ cat unmapped.txt
GAGAGA
TCTCTC
```

**Comment by ferayd** [comment]
Hi @ch4rr0 , I tested the bug_fixes branch, and it works now. Thanks.
Are you going to release a new Bowtie version soon?

**Comment by ferayd** [comment]
Thanks @ch4rr0, the new release (1.3.0) works well.
