### ISSUE TITLE
Renaming the v1.2.3 src archive to "bowtie-1.2.3-src.zip"?

### ISSUE THREAD

**Issue by junaruga** [BenLangmead/bowtie#101]
Hello,
I have a suggestion.

There is "bowtie-src-x86_64.zip" in https://sourceforge.net/projects/bowtie-bio/files/bowtie/1.2.3/ .

Is it possible to rename the "bowtie-src-x86_64.zip" to "bowtie-1.2.3-src.zip" file name like other version's source files? I think the name "src-x86_64" is not correct. The source itself does not depend on the CPU architecture such as "x86_64".

The URL has been used to download the archive in [bowtie RPM package's recipe file](https://src.fedoraproject.org/rpms/bowtie/blob/master/f/bowtie.spec#_9).

Following commands are succeeded.

```
$ wget http://downloads.sourceforge.net/bowtie-bio/bowtie-1.0.1-src.zip
$ wget http://downloads.sourceforge.net/bowtie-bio/bowtie-1.2.2-src.zip
```

But following command is failed.

```
$ wget http://downloads.sourceforge.net/bowtie-bio/bowtie-1.2.3-src.zip
--2020-01-05 13:36:11--  http://downloads.sourceforge.net/bowtie-bio/bowtie-1.2.3-src.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-01-05 13:36:12 ERROR 404: Not Foun
```

Thank you.

**Comment by mschilli87** [comment]
I'd suggest linking over renaming in case anyone already depends on the old name.

**Comment by junaruga** [comment]
I agree with the suggestion.

**Comment by ch4rr0** [comment]
The x86_64 should not have been in the file name. That was a mistake on my part.

**Comment by junaruga** [comment]
While the bowtie-1.2.3 archive is still not renamed, bowtie-1.3.0 archive name is `bowtie-$version-src.zip`. Thank you for that.

```
$ wget http://downloads.sourceforge.net/bowtie-bio/bowtie-1.3.0-src.zip
...
2020-07-26 10:39:43 (386 KB/s) - ‘bowtie-1.3.0-src.zip’ saved [7469740/7469740]
```

A difference for the bowtie 1.3.0 archive comparing from previous archives is that `bowtie-1.2.2-src.zip`'s top directory is `bowtie-1.2.2` (`bowtie-$version`). `bowtie-1.3.0-src.zip` is top directory is `bowtie-1.3.0-src` (`bowtie-$version-src`).

bowtie-1.2.2 directory is created.

```
$ unzip bowtie-1.2.2-src.zip
```

bowtie-1.3.0-src directory is created.

```
$ unzip bowtie-1.3.0-src.zip
```
