### ISSUE TITLE
Invalid double quote character is used in the code

### ISSUE THREAD

**Issue by junaruga** [BenLangmead/bowtie#104]
I faced following error on bowtie 1.2.3 (not bowite2) with gcc 10.0.1.

```
processor_support.h:52:22: error: extended character “ is not valid in an identifier
   52 |         std::cerr << “ERROR: please define __cpuid() for this build.\n”;
      |                      ^
processor_support.h:52:72: error: extended character ” is not valid in an identifier
   52 |         std::cerr << “ERROR: please define __cpuid() for this build.\n”;
      |       
```

Because `processor_support.h`'s first double quote `“` is not ascii code `"`.

```
        std::cerr << “ERROR: please define __cpuid() for this build.\n”;
```

Searching with the `“`, following files are the files that have the character.
`processor_support.h` is affected to build it.

```
$ grep -rl '“' 
README.md
MANUAL
doc/manual.html
doc/website/manual.ssi
doc/website/recent_news.ssi
processor_support.h
example/reads/combined_reads.bam
```

The solution could be like this.

```
$ sed -i 's/“/"/g' processor_support.h
```

**Comment by junaruga** [comment]
`”` (another invalid double quote character) is also included.

```
$ grep -rl "”"
.git/objects/pack/pack-256fee39b70e12022911f208b4786a5dcc5bbaf6.pack
doc/manual.html
doc/website/manual.ssi
processor_support.h
indexes/e_coli.1.ebwt
```

The solution.

```
$ sed -i 's/”/"/g' processor_support.h
```

**Comment by ch4rr0** [comment]
Thanks for pointing this out. I have pushed a fix for bowtie2 will update bowtie soon.

**Comment by junaruga** [comment]
I would close this ticket, as I confirmed it was fixed by https://github.com/BenLangmead/bowtie/commit/777cda38361c39ad0014c316f1d5e49b8da2c9f2 . Thank you!
