### ISSUE TITLE
Unmapped reads not suppressed using --no-unal and possibly wrong stderr stats

### ISSUE THREAD

**Issue by benplm** [BenLangmead/bowtie#107]
I've found that, in spite of using the option `--no-unal`, unmapped reads are still reported in the output file. This is the command I ran, single-ended alignment suppressing multimapping reads, using bowtie 1.2.3:
```
zcat sample.fastq.gz | bowtie -S -p 4 -m 1 --no-unal --best --strata -v 3 bowtie_index/hg38 - 2> sample.bowtie.stats | samtools view -Sb -@ 2 -o sample.bam
```

Unmapped reads can be found in the output bam file:
```
$ samtools view -f 4 -c sample.bam
1443826
```

Curiously, the number of unmapped reads matches with the number of alignments suppressed due to -m, rather than the number of reads that failed to align:
```
$ cat sample.bowtie.stats
# reads processed: 23622418
# reads with at least one reported alignment: 20671144 (87.51%)
# reads that failed to align: 1507448 (6.38%)
# reads with alignments suppressed due to -m: 1443826 (6.11%)
Reported 20671144 alignments
```

As expected, I do not have any non-primary alignment in the output file:
```
$ samtools view -f 256 -c sample.bam
0
```

So, since i) I have unmapped reads on my output bam file and ii) stderr reports the number of unmapped reads as the number of suppressed multimapping reads, could it be that not only `--no-unal` fails to suppress unmapped reads, but also the stderr statistics are wrong or misplaced?

**Comment by ch4rr0** [comment]
I may have committed a change for this just after v1.2.3 was released. If possible can you checkout and compile the code in `bug_fixes` branch to see if it addresses the issue?

**Comment by benplm** [comment]
I did a couple more of test:

First I tried to omit `--no-unal`, with bowtie 1.2.3
```
bowtie -S -p 4 -m 1 --best --strata -v 3 bowtie_index/hg38 sample.fq 2> stderr.txt | samtools view -b -o sample.bam
```

Alignments suppressed due to -m are actually not suppressed (see output of samtools), but reported as unaligned in the output bam. So this is the cause of the issue in the first post, that is, when using `--no-unal` there are still unaligned reads in the output bam due to this bug.
```
$ cat stderr.txt
# reads processed: 5775858
# reads with at least one reported alignment: 4881852 (84.52%)
# reads that failed to align: 573710 (9.93%)
# reads with alignments suppressed due to -m: 320296 (5.55%)
Reported 4881852 alignments
```
```
$ samtools view -f 4 -c sample.bam
894006
```

Then I tried with the `bug_fixed` branch, as you suggested. Same command as above.

samtools now report a number of unmapped reads equal to the reads that failed to align, and no non-primary alignments, so it seems fixed. Also, I noticed that now reads with at least one alignment include those suppressed due to -m, which makes sense.
```
$ cat stderr.txt
# reads processed: 5775858
# reads with at least one alignment: 5202148 (90.07%)
# reads that failed to align: 573710 (9.93%)
# reads with alignments suppressed due to -m: 320296 (5.55%)
Reported 4881852 alignments
```
```
$ samtools view -f 4 -c sample.bam
573710
$ samtools view -f256 -c sample.bam
0
```

Finally, if I run the `bug_fixes` version with `--no-unal`, 
```
$ samtools view -f 4 -c sample.bam
0
$ samtools view -f256 -c sample.bam
0
```
I get the same stderr as above, and no unmapped reads in the output bam.
So I guess it's fixed.
Thanks, I'll look forward to the next release!
