### ISSUE TITLE
Makefile `install` target

### ISSUE THREAD

**Issue by wookietreiber** [BenLangmead/bowtie#11]
Without, it is really hard to figure out which files are actually needed for a distribution.

**Comment by sjackman** [comment]
:+1:

**Comment by kotoroshinoto** [comment]
I agree, make sure to use a PREFIX variable rather than hardcoding paths with /usr in mind.

**Comment by wookietreiber** [comment]
See https://github.com/BenLangmead/bowtie2/pull/25 for the effort on bowtie2. Once this gets merged, I'll also prepare this for this project.

**Comment by sjackman** [comment]
Great. Thanks.

**Comment by BenLangmead** [comment]
hey @wookietreiber -- please feel free to submit similar pull request here and we'll merge.  Thanks for the help!

Best,
Ben
