### ISSUE TITLE
Install bowtie

### ISSUE THREAD

**Issue by paolabc** [BenLangmead/bowtie#110]
I'm new int this field. I tried to install bowtie-1.2.3 for ubuntu system. I downloaded the source code and extract this in a new directory.  I  acessed the  directory that has the extract files and run make command to get compilation of this software, but there's no makefile in there. In the site, it's describing to just this steps. I need to tried ./configure or something like this?

**Comment by junaruga** [comment]
There is `Makefile`. You do not need to run `./configure` or something.
Could you explain what you did by using the command lines?

```
$ unzip bowtie-src-x86_64.zip 
Archive:  bowtie-src-x86_64.zip
   creating: bowtie-1.2.3/
  inflating: bowtie-1.2.3/sam.h      
  inflating: bowtie-1.2.3/chaincat.cpp  
...

$ cd bowtie-1.2.3/

$ ls -l Makefile 
-rw-r--r-- 1 jaruga jaruga 13380 Jul  6  2019 Makefile
```
