### ISSUE TITLE
What is the sense of third_party/cpuid.h

### ISSUE THREAD

**Issue by tillea** [BenLangmead/bowtie#117]
Hi,
when building the Debian package I noticed that cpuid.h breaks the build on certain architectures (for instance for [arm64](https://buildd.debian.org/status/fetch.php?pkg=bowtie&arch=arm64&ver=1.3.0%2Bdfsg-3&stamp=1602516597&raw=0) ).  When deleting this file gcc will simply fall back to the system cpuid.h which works.  Given that the system cpuid.h is way more recent than a code copy if (possibly) 2009 I wonder whether it for what purpose this is included into bowtie source code.
Kind regards, Andreas.

**Comment by ch4rr0** [comment]
This will be removed in the coming release.

**Comment by ch4rr0** [comment]
This file has been removed as of v1.3.1.
