### ISSUE TITLE
small bug in bowtie script affecting identification of large indexes

### ISSUE THREAD

**Issue by pdblood** [BenLangmead/bowtie#12]
The current bowtie script is setting its last argument as the index file basename, which, for a command like this

`bowtie e_coli reads/e_coli_1000.fq`

will return the name of the reads file as the index basename, rather than the basename provided on the command line.

This doesn't matter for small indexes, because the small index binary is called by default, and this binary is able to find the appropriate indexes.  However, this issue causes bowtie to miss large indexes, unless the --large-index flag is used.

For the command above, this could be fixed by changing:

`idx_basename = arguments[-1]`

to

`idx_basename = arguments[-2]`

but this would still fail for large indexes with commands like:

`bowtie -t e_coli reads/e_coli_1000.fq e_coli.map`

This issue surfaced for me while attempting some large Trinity assemblies that call bowtie.  With the introduction of large indexes, it looks like a different method should be used for identifying idx_basename in the bowtie command.

```
if '--large-index' in options:
        bin_spec = os.path.join(ex_path,bin_l)
    elif len(arguments) >= 1:
        idx_basename = arguments[-1]
        large_idx_exists = os.path.exists(idx_basename + idx_ext_l)
        small_idx_exists = os.path.exists(idx_basename + idx_ext_s)
        if large_idx_exists and not small_idx_exists:
            bin_spec = os.path.join(ex_path,bin_l)
```

**Comment by val-antonescu** [comment]
You are right. We fixed this for the next release. We will have a release soon which will include this fix.

thank you,
Val
