### ISSUE TITLE
Add support for named pipes / process substitution

### ISSUE THREAD

**Issue by nathanweeks** [BenLangmead/bowtie#2]
bowtie-1.0.0 currently does not support named pipes or process substitution. These are useful when one wants to uncompressing/trim/filter reads on-the-fly, but can't pipe all input data to bowtie's stdin (e.g., when aligning mates).  

Here's an example of the error that occurs when the shell (ksh93 in this case) implements process substitution using named pipes:

```
$ bowtie -S TRANS -1 <(gzip -dc left.fq.gz | my-filter-script) -2 <(gzip -dc right.fq.gz | my-filter-script)
...
@PG     ID:Bowtie       VN:1.0.0        CL:"bowtie -S TRANS -1 /tmp/ksh.f0fiaun -2 /tmp/ksh.f0lliut"
Warning: Could not open read file "/tmp/ksh.f0fiaun" for reading; skipping...
Command: bowtie -S -1 /tmp/ksh.f0fiaun -2 /tmp/ksh.f0lliut TRANS
```

Tracing system calls with the "truss" command revealed the following sequence of open and close commands:

```
36612: open("/tmp/ksh.f0fiaun",O_RDONLY,0666)    = 3 (0x3)
36612: open("/tmp/ksh.f0eo6sb",O_RDONLY,0666)    = 4 (0x4)
...
36612: close(3)                                  = 0 (0x0)
36612: open("/tmp/ksh.f0lliut",O_RDONLY,0666)    ERR#2 'No such file or directory'
```

The named pipe /tmp/ksh.f0fiaun was opened, closed (after which ksh removes the named pipe), and opened again (error, since the named pipe no longer exists). If, instead of using process substitution, named pipes are directly created by the user with the mkfifo command, then there is no error upon the second open(), but bowtie blocks while trying to read from the named pipe, as there would be no writer process (the writer would have received a SIGPIPE when bowtie close()es the named pipe and would have probably terminated).

Updating bowtie to call open() / fopen() only once for a given input reads file would resolve the issue.

**Comment by val-antonescu** [comment]
I believe this issue is solved in the meantime. A quick test example run on my box:
./bowtie hg19  <(zcat ~/data/ERR324434_slice.fq.gz) -S /dev/null
# reads processed: 100000
# reads with at least one reported alignment: 85808 (85.81%)
# reads that failed to align: 14192 (14.19%)
Reported 85808 alignments to 1 output stream(s)

**Comment by pati-ni** [comment]
are you sure this is resolved? you should really check it with a paired end scenario cause that is the case where it can block.

**Comment by jeffpkamp** [comment]
I realize this is a very old thread that is still going, but I thought I would add this note.

it worked when I run it using the method above ( <(shell command) ), but when I use a FIFO buffer it seems to only read a few hundred lines and then break the pipe when I use it for paired-end reads.

```
mkfifo read1
mkfifo read2
zcat file1_R1.gz file2_R1.gz file3_R1.gz > read1 &
zcat file1_R2.gz file2_R2.gz file3_R2.gz > read2 &
bowtie  --chunkmbs 512 -m 1 -t --best -q -S -l 32 -e 80 -n 2 10000 -p $CORES hg38 -1 read1 -2 read2 
```
