### ISSUE TITLE
bowtie_inspect.cpp:197: bad delete ?

### ISSUE THREAD

**Issue by dcb314** [BenLangmead/bowtie#20]
bowtie_inspect.cpp:197:2: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]

From

   delete buf;

to

   delete [] buf;

**Comment by BenLangmead** [comment]
Thank you!  Just fixed in the master branch.  Fix will be present in the next release.

Best,
Ben
