### ISSUE TITLE
Trying to run bowtie source files

### ISSUE THREAD

**Issue by AgazW** [BenLangmead/bowtie#24]
I would like to know  how to run the source files of bowtie. I downloaded the source code files and I am trying to run the source code files but till now i am not successful. There are many CPP and python files such as 
```
bowtie_build_main.cpp
bowtie.py 
```
and many others. 

When i try to run  
```
g++ bowtie_build_main.cpp -o bowtie_build_main
```

I get the following error:
```
/tmp/ccpcVAHD.o: In function `main':
bowtie_build_main.cpp:(.text+0x355): undefined reference to `bowtie_build'
bowtie_build_main.cpp:(.text+0x420): undefined reference to `bowtie_build'
collect2: error: ld returned 1 exit status
```
or when i try to run **bowtie.py** 
 I get 

```
python: can't open file 'bowtie.py': [Errno 2] No such file or directory
```
How can i run the source code files . Thanks

**Comment by val-antonescu** [comment]
Hi Agaz,

I will close this since is not a bowtie issue. I am guessing you should ask your sysadmin for help, or at least someone who is more familiar with handling software. The bowtie manual describes the options you have for properly building and using this tool.

good luck
Val
