### ISSUE TITLE
License

### ISSUE THREAD

**Issue by serge2016** [BenLangmead/bowtie#30]
Hello.
The license in the file in not the same as here: https://tldrlegal.com/license/artistic-license-1.0
E.g.: p.8 is absent.

**Comment by BenLangmead** [comment]
You're right.  It's as though the license on Bowtie is a mash-up of that one you linked to and this one:

https://tldrlegal.com/license/open-group-test-suite-license-(ogtsl)#fulltext

We'll do a little digging to figure out what happened and how best to fix.

**Comment by BenLangmead** [comment]
Update: we plan to switch to the Artistic 2.0 license in a future release.  Not this upcoming release (1.2.1), but the next one after that.  In the release notes for 1.2.1, we will advertise this fact so it doesn't come as a surprise.
