### ISSUE TITLE
Add Support for gzipped FASTQ Files

### ISSUE THREAD

**Issue by DarioS** [BenLangmead/bowtie#31]
It would be convenient if the input files could be compressed, when Bowtie is used within RSEM and I have no control of the Bowtie command line being executed.

**Comment by antonkratz** [comment]
+1 this.
Support for input fastq as gz files would be terribly useful.
I know there are various patched versions of bowtie which add gz support, for example this one (https://github.com/earonesty/bowtie) and others, but those are all very much out of date.
I was trying to do this, I believe the necessary code would need to go into pat.h, maybe related to class PatternSource (?)... I am not at a stage yet where I could make such changes to the bowtie source - it would be great if someone could add this.

**Comment by ch4rr0** [comment]
This feature could be implemented in the bowtie wrapper script similar to how Bowtie 2 does it. How ever if RSEM calls the bowtie binaries directly (not recommended) we could consider implementing this at the source level. I would like to hear your thoughts on this.

**Comment by antonkratz** [comment]
I do not want to hijack this issue - I am not using RSEM - I just want gz support b/c I am dealing with very large fastq files and the constant unpacking and packing takes so much time and space - shall I open a separate issue? For me an implementation in the wrapper script would be sufficient.

**Comment by DarioS** [comment]
I'm not using RSEM either, but a lot of other people do. I think implementing it at the source level is best, because it's the most general use case. Anything that makes using the software easier makes getting citations of it easier ...

**Comment by antonkratz** [comment]
ch4rr0, which file in the repo is "the bowtie wrapper script" you are referring to?

**Comment by BenLangmead** [comment]
Update: This is coming in v1.2.1, to be released soon.

**Comment by mbsimonovic** [comment]
is this implemented or not?

**Comment by ch4rr0** [comment]
Yes, Bowtie has support for compressed reads.

**Comment by mbsimonovic** [comment]
well how then? seems like it expects a file, -c switch and reading from stdin (pipe from gunzip) doesn't seem to work.

**Comment by DarioS** [comment]
You don't need to use pipes or any unzipping programs. Just put the path to the compressed FASTQ files in the sample place you would put uncompressed files. It is handled automatically by Bowtie.

Unfortunately, this information is not present in Bowtie Manual.

**Comment by mbsimonovic** [comment]
I have a fasta file, not fastq, and it cannot index it:
$ bowtie-build genome.fa.gz genome
Input files DNA, FASTA:
  genome.fa.gz
Reading reference sizes
Warning: Encountered reference sequence with only gaps
Error: No unambiguous stretches of characters in the input.  Aborting...
  Time reading reference sizes: 00:00:00
