### ISSUE TITLE
Wont read fastq file from STDIN in v1.2.0

### ISSUE THREAD

**Issue by ppericard** [BenLangmead/bowtie#37]
Hi,
Since the update to v1.2.0 I cannot complete alignments runs that worked with bowtie v1.1.2 and that read alignment files from STDIN.

e.g. 
Works with Bowtie 1.1.2:
 cat reads.left.fastq | bowtie --phred33-quals -t -p 24 -n 3 -l 20 -e 300 --best --sam --chunkmbs 128 --minins 101 --maxins 400 default_db -1 - -2 reads.right.fastq > test

But does not work with Bowtie 1.2.0:
Time loading reference: 00:00:00
Time loading forward index: 00:00:04
Time loading mirror index: 00:00:02
Error: reads file does not look like a FASTQ file
Error: reads file does not look like a FASTQ file
Error: reads file does not look like a FASTQ file
...

But, of course this does work in both version:
bowtie --phred33-quals -t -p 24 -n 3 -l 20 -e 300 --best --sam --chunkmbs 128 --minins 101 --maxins 400 default_db -1 reads.left.fastq -2 reads.right.fastq > test

**Comment by ch4rr0** [comment]
I have pushed a change to the master branch that should resolve this issue. If you're building from source feel free to pull this change. If not I will have a incremental release planned in the coming weeks which will include this change. I will keep the issue open until then.

**Comment by ppericard** [comment]
Thanks ^^
