### ISSUE TITLE
Bowtie cannot be killed on MacOS

### ISSUE THREAD

**Issue by jcrbloch** [BenLangmead/bowtie#40]
I am running bowtie2.2.9 on MacOS 10.12.2. I wanted to abort the program, which was running in the background, but there was no way to do so. I tried to "Quit" and "Force Quit" through the task manager but the program kept running. Then I tried kill -9 and kill -15 in the terminal window, but the program still kept running at 100% CPU usage. The only way to stop the program was to reboot my machine. I have never seen this with any program. Does anyone knows the problem?

**Comment by BenLangmead** [comment]
Can you provide the exact arguments you used to run Bowtie 2?

**Comment by BenLangmead** [comment]
Haven't heard anything so will close for now.  Please reopen/comment if you continue to have this issue
