### ISSUE TITLE
problem with fastq input

### ISSUE THREAD

**Issue by jchenpku** [BenLangmead/bowtie#43]
I have a fastq file like this, it's from a crispr screening:
@ERR376999.1 1/1
CCTGACAGTCTCCCGCGCT
+
EEEEEFFEFEEFEEEEEEF
@ERR376999.2 2/1
CATTTATTTTTCGGAGTGC
+
EEEEEEFEEFEEEEEFEFF
@ERR376999.3 3/1
AGTTCAAAATCCAGTCTAC

The file can be aligned with bowtie2 without any problem but when I'm trying to align it using bowtie, it reported error:
Saw ASCII character 10 but expected 33-based Phred qual.

I tried the untrimmed fastq file, it also reported error:
Error: reads file does not look like a FASTQ file

the untrimmed file looks like this:
@ERR376999.1 1/1
CTTGTGGAAAGGACGAAACACCGCCTGACAGTCTCCCGCGCTGTTTTAGA
+
B@CDDDDEEEEEEEEEEEEEEFEEEEEEFFEFEEFEEEEEEFEEEEEDED
@ERR376999.2 2/1
CTTGTGGAAAGGACGAAACACCGCATTTATTTTTCGGAGTGCGTTTTAGA
+
B@CDDDDEDEEEEEEEEEEEFFFEEEEEEFEEFEEEEEFEFFEEEFFEEE
@ERR376999.3 3/1
CTTGTGGAAAGGACGAAACACCGAGTTCAAAATCCAGTCTACGTTTTAGA

what could be the problem? Thanks

**Comment by dnbh** [comment]
Your sequence and quality scores are of different lengths, both trimmed and untrimmed. These are malformed fastq files and any reasonable program will refuse to process them.

Character "10" is the newline character; it is expecting your reads to be of the same length and is finding that the line ends too soon.

**Comment by BenLangmead** [comment]
Could you share the file that gives bowtie the problem?  Or ideally just a small part of the file that causes the problem?

**Comment by meecle** [comment]
I had the same problem. 
Saw ASCII character 10 but expected 33-based Phred qual.
Aborted (core dumped)

**Comment by meecle** [comment]
@E00552:163:HLCJLCCXY:2:1101:2767:1502 1:N:0:GATCGTGT
GCGATCTCCACGGAGCAGCAG
+
JJJJJJJFF-<FA7FJJF77F
@E00552:163:HLCJLCCXY:2:1101:2869:1502 1:N:0:GATCGTGT
GCATAGATGAGATGACTCAG
+
J7JJJJJJJJJJJ<A--7<-
@E00552:163:HLCJLCCXY:2:1101:8014:1520 1:N:0:GATCGTGT
AGCTGATGTGCATTAGCACT
+
JJJJJJJJJJJJJJJJFJJJ
@E00552:163:HLCJLCCXY:2:1101:8481:1520 1:N:0:GATCGTGT
CAATGCTACGTATCGATCTG
+
JJJJJJJJJJJJAJJJ<JJJ

**Comment by nekrut** [comment]
This is likely because some of fastq entries have empty (length=0) sequences. This could, for example, be an artifact of running cutadapt

**Comment by dnbaker** [comment]
The samples above clearly have sequences and qualities of different lengths, @nekrut , but it's good to know that you've had problems with empty fastq sequences as well.

I personally suggest masking bases rather than removing them when using cutadapt because it preserves cycle information.
