### ISSUE TITLE
Bowtie 1.2 error when using symlink

### ISSUE THREAD

**Issue by egaffo** [BenLangmead/bowtie#44]
If I call bowtie using a symlink in Linux (Ubuntu 14.04 LTS) it does not work. I used the binary version. Also the "legacy" package shows the same error. 

$ ln -s bowtie-1.2-legacy/bowtie bowtie
$ ./bowtie
Traceback (most recent call last):
  File "./bowtie", line 91, in <module>
    main()            
  File "./bowtie", line 88, in main 
    os.execv(bin_spec, bowtie_args)  
OSError: [Errno 2] No such file or directory

With v1.1.2 it is working.

Enrico

**Comment by BenLangmead** [comment]
Is the `bowtie-align-s` binary present in the same directory as the target (linked to) `bowtie` script when you run the `bowtie` symlink?

**Comment by egaffo** [comment]
Yes, it is present, as it is unpacked from the archive. To reproduce the error, these are exactly the commands I used:
`wget https://github.com/BenLangmead/bowtie/releases/download/v1.2.0/bowtie-1.2-linux-legacy-x86_64.zip`
`unzip bowtie-1.2-linux-legacy-x86_64.zip`
`ln -s bowtie-1.2-legacy/bowtie`
`./bowtie`

**Comment by BenLangmead** [comment]
Thank you for pointing this out.  I think this commit will fix it:
https://github.com/BenLangmead/bowtie/commit/3ac6ea20db43764815714758f5bf76bb96ae72cd

And that will be present in the next release (1.2.1).
