### ISSUE TITLE
explanation for differences between bowtie-1.2-linux-legacy-x86_64.zip and bowtie-1.2-linux-x86_64.zip

### ISSUE THREAD

**Issue by ndaniel** [BenLangmead/bowtie#45]
It would be great to have somewhere explained also in the manul the differences between `bowtie-1.2-linux-legacy-x86_64.zip` and `bowtie-1.2-linux-x86_64.zip` and when one should be used over the other one!

**Comment by nylander** [comment]
Info hidden in the file `NEWS`.

**Comment by BenLangmead** [comment]
I agree we should explain this in the manual

**Comment by ch4rr0** [comment]
As of 1.2.1 we no longer offer "legacy" binaries. All prepackaged binaries now use the TBB threading library.
