### ISSUE TITLE
Elimiate -f for bowtie-build

### ISSUE THREAD

**Issue by DarioS** [BenLangmead/bowtie#47]
By default, it expects FASTA files, so it's unclear why there is a `-f` flag in the Options section. Also, for `bowtie`, it expects FASTQ files by default, but it has a `-q` flag in its Options section. These two options seem redundant.

**Comment by mschilli87** [comment]
Consider if I run `bowtie` through a script that allows me to specify `bowtie` options.
If this script was written with a hard-coded `-q` in the `bowtie` command line, putting `-f` in the 'bowtie-options'-parameter of the script could allow me to run it on FASTA files without the need to change the script itself (making it easier to update that script to a newer version later on, for example).

So while I can image situations where these come in handy, but see no disadvantage (except for maintaing a handful extra lines of parameter parsing), I vote against removing these options.

**Comment by BenLangmead** [comment]
I agree with @mschilli87 that the current situation is desirable, as the option can be used to override options specified earlier on the command-line.
