### ISSUE TITLE
Option To Exclude Unmapped Reads From SAM

### ISSUE THREAD

**Issue by DarioS** [BenLangmead/bowtie#49]
Currently, unmapped reads are included in the SAM file. I have a scenario where 99% of the reads won't map to the reference sequences used (i.e. mapping only to a gene family). This creates unnecessarily large files which need to be filtered to reduce their size (e.g. `sed`). It'd be nice to be able to specify an option to `bowtie` that would prevent it from ever outputting those reads to the SAM file to increase the speed of the pipeline by doing less postprocessing (filtering) to the resulting SAM file produced by `bowtie`.

**Comment by ch4rr0** [comment]
I have committed changes for a command line option, `--no-unal`, that enables this behavior. The changes will be out in the soon-to-be-released Bowtie 1.2.1. Thank you.
