### ISSUE TITLE
Do fast bowtie with option -c 

### ISSUE THREAD

**Issue by OrsonMM** [BenLangmead/bowtie#50]
Hello 

I tried to use these command like a subrutine in my python script 
seq1 = CATGTAGCTAG
subprocess.call(bowtie -c  index.bwt   seq1)

But it takes around 3s. for each search, And I have a lot of seqs. And I need do fast. Exist a possible do more efficient  in my code. 

Pd: I now that if I use a file that contain all my seqs,  bowtie is fast and efficient. 

Saludos.

**Comment by BenLangmead** [comment]
I think you're stuck putting all your queries in a file and running them all at once, as you suggest.  I understand that might not fit your use case.  The way you're running `bowtie` repeatedly, you're unavoidably causing the executable to start up repeatedly and load the index repeatedly and those things take a lot of time compared to aligning a single read.

**Comment by BenLangmead** [comment]
I'll close this for now.  Please reopen/comment if you can't get reasonable performance with `-r` or a similar mode.
