### ISSUE TITLE
Version 1.2 Causes Improperly Paired Alignments Error in RSEM

### ISSUE THREAD

**Issue by DarioS** [BenLangmead/bowtie#52]
Alignments generated by version 1.2 - but not version 1.0.1 - cause an error to be emitted by `rsem-parse-alignments` and therefore preventing transcript estimation from going ahead.

```
rsem-parse-alignments /home2/starfish/RSEM/starfish S1.temp/S1 S1.stat/S1 S1.temp/S1.bam 3 -tag XM
Warning: Detected a read pair whose two mates have different names--3NH4HQ1:246:C59MKACXX:5:1101:2705:2182 and 3NH4HQ1:246:C59MKACXX:5:1101:1263:2096!
Read 3NH4HQ1:246:C59MKACXX:5:1101:2705:2182: The two mates do not align to a same transcript! RSEM does not support discordant alignments.
```

Another user of RSEM had the exact same problem and he had to [abandon Bowtie in favour of kallisto](https://groups.google.com/d/msg/trinityrnaseq-users/vzFUTSSWnRs/ZZr_478JBgAJ) because of this blocker. He also found that the problem could be avoided by using Bowtie 2. Can this regression be fixed in Bowtie 1 by version 1.3?

**Comment by ch4rr0** [comment]
A temporary solution would be to run bowtie with one thread. I am looking into a long term fix.

Works
`./rsem-calculate-expression --bowtie-path </path/to/bowtie> --calc-ci **-p 1** --paired-end reads_1.fq reads_2.fq lv_bt1 out`

Fails
`./rsem-calculate-expression --bowtie-path </path/to/bowtie> --calc-ci **-p 3** --paired-end reads_1.fq reads_2.fq lv_bt1 out`

There will be a slow-down, so apologies for the inconvenience.

**Comment by ch4rr0** [comment]
I pushed a change to the `bug_fixes` branch that addresses this issue. It would be appreciated if you help confirm that it works.

**Comment by DarioS** [comment]
I tried the suggested branch bowtie version on my dataset and the described problem is gone. Hope the changes can be in a release soon.

**Comment by ch4rr0** [comment]
This change was included as part of our most recent release.
