### ISSUE TITLE
Could not locate a Bowtie index corresponding to basename "genome"

### ISSUE THREAD

**Issue by pandafish123** [BenLangmead/bowtie#57]
Hi
Recently, i was using bowtie 1.2.1.1 to map fastq files to mouse genome. The following are my command lines.
 bowtie-build --threads 10 Mus_musculus.GRCm38.dna_rm.toplevel.fa  genome
![image](https://user-images.githubusercontent.com/19991955/27784824-274a8ebc-600e-11e7-9a36-aa30fa62eace.png)

nohup bowtie genome  /data/disk4/chip/SRR3051599.fastq   -S nibpl.sam -p 20 -m 1 &

However, i got error message  "Could not locate a Bowtie index corresponding to basename "genome" 

I do not know how to solve this problem.

Appreciate for your help

**Comment by ch4rr0** [comment]
Were the two command lines ran in sequence? Is it possible that you did a `cd` before running the second?

**Comment by pandafish123** [comment]
Thanks for your reply.
Yes ,they were ran in sequence. By the way, does this matters?  Besides, i've tried put the fastq files under the index. It does't work either.

**Comment by ch4rr0** [comment]
You built a large index and therefore need to specify the `--large-index` parameter when running your alignment. Bowtie will try to find a small index if that parameter is not specified hence the error. Apologies for the significant delay between responses, but if this was somehow still and issue please let me know adding the `--large-index` parameter resolves it.

**Comment by ch4rr0** [comment]
I am going to assume that this is no longer an issue. Feel free to reopen the issue if you feel otherwise.
