### ISSUE TITLE
Error for colorspace data

### ISSUE THREAD

**Issue by rnakato** [BenLangmead/bowtie#61]
Hi,

After version 1.2.0, an error occurs when aligning colorspace data generated by SOLiD.
When using version 1.1.2, there is no problem.
Could you solve this problem?

```
$ bowtie-1.2.1.1/bowtie -C hg19-cs sample.fastq -n2 -k1 > /dev/null
Reads file contained a pattern with more than 1024 quality values.
Please truncate reads and quality values and and re-run Bowtie
terminate called after throwing an instance of 'int'
```

**Comment by BenLangmead** [comment]
Could you share a small example of a colorspace fastq file that yields this error?

**Comment by rnakato** [comment]
I attach a small sample I used.
[sample.fastq.gz](https://github.com/BenLangmead/bowtie/files/1355035/sample.fastq.gz)
This file is a part of ChIP-seq data for S. serevisiae (SRR1555011).

Many thanks!

**Comment by ch4rr0** [comment]
This change was included as part of our most recent release.
