### ISSUE TITLE
ftp server for indexes is down?

### ISSUE THREAD

**Issue by iriet** [BenLangmead/bowtie#67]
I'm trying to get the bowtie1 indexes off of the link from the tutorials site:
http://bowtie-bio.sourceforge.net/tutorial.shtml

The download fails, and when I try to connect to the ftp server with Filezilla, I seem not able to connect.

**Comment by ch4rr0** [comment]
The servers are fine. What error are you getting?

**Comment by BenLangmead** [comment]
We'll close this for now.  Please comment if you have trouble again.
