### ISSUE TITLE
wrong number of reads processed

### ISSUE THREAD

**Issue by sklasfeld** [BenLangmead/bowtie#70]
When I input paired end reads each with 44 million reads, bowtie reports that it processed 67 million reads. The only parameters I used were `--no-unal -S --chunkmbs 200 --best -m 1`. I had installed bowtie from bowtie-1.2.1.1-linux-x86_64.zip. Any ideas of why this is the case?

**Comment by ch4rr0** [comment]
This is a known bug in this version of bowtie. We have already pushed a commit for the issue that will be in the next bowtie release. In the meantime you can try using the beta build available [here.](https://github.com/BenLangmead/bowtie/releases/download/v1.2.2-beta/bowtie-1.2.2-beta-linux-x86_64.zip)

**Comment by ndaniel** [comment]
This is probably the same as this: https://github.com/BenLangmead/bowtie/issues/55

**Comment by ch4rr0** [comment]
This change was included as part of our most recent release.
