### ISSUE TITLE
Cannot find bowtie index

### ISSUE THREAD

**Issue by sagnikbanerjee15** [BenLangmead/bowtie#71]
Hello,

I am using bowtie version 1.2.1.1 to map my short reads to the barley genome. The barley genome is about 5Gb long (containing some N's) hence bowtie creates a long index when the command bowtie-build is issued. The bowtie-build completes perfectly without any error. When I attempt to map the reads back to the index then the trouble starts. It keeps giving me the following error.

Could not locate a Bowtie index corresponding to basename "bowtie1_index"
Command: bowtie-align --wrapper basic-0 -f bowtie1_index T1_0_R1.consolidated.fasta alignment 

I have tried with a previous version of bowtie (1.1.2) but had no luck. I also copy pasted my reads file in the same directory as the indices but it still did not work. The ls -lh of the index directory looks like this.

[sagnik@speedy2 genome]$ ls -lh
total 32G
-rwxrwxrwx. 1 sagnik domain users  1.2G Dec  5 06:02 bowtie1_index.1.ebwtl
-rwxrwxrwx. 1 sagnik domain users 1020M Dec  5 06:02 bowtie1_index.2.ebwtl
-rwxrwxrwx. 1 sagnik domain users   19M Dec  5 05:33 bowtie1_index.3.ebwtl
-rwxrwxrwx. 1 sagnik domain users 1020M Dec  5 05:33 bowtie1_index.4.ebwtl
-rwxrwxrwx. 1 sagnik domain users  1.2G Dec  5 06:34 bowtie1_index.rev.1.ebwtl
-rwxrwxrwx. 1 sagnik domain users 1020M Dec  5 06:34 bowtie1_index.rev.2.ebwtl
-rw-r--r--. 1 sagnik domain users  1.4G Dec  5 07:44 bowtie2_index.1.bt2l
-rw-r--r--. 1 sagnik domain users  2.0G Dec  5 07:44 bowtie2_index.2.bt2l
-rw-r--r--. 1 sagnik domain users   19M Dec  5 07:10 bowtie2_index.3.bt2l
-rw-r--r--. 1 sagnik domain users 1020M Dec  5 07:10 bowtie2_index.4.bt2l
-rw-r--r--. 1 sagnik domain users  1.4G Dec  5 08:18 bowtie2_index.rev.1.bt2l
-rw-r--r--. 1 sagnik domain users  2.0G Dec  5 08:18 bowtie2_index.rev.2.bt2l
-rw-r--r--. 1 sagnik domain users  3.4G Sep 30 15:18 hisat2_index.1.ht2l
-rw-r--r--. 1 sagnik domain users  4.0G Sep 30 15:18 hisat2_index.2.ht2l
-rw-r--r--. 1 sagnik domain users   19M Sep 30 14:16 hisat2_index.3.ht2l
-rw-r--r--. 1 sagnik domain users 1020M Sep 30 14:16 hisat2_index.4.ht2l
-rw-r--r--. 1 sagnik domain users  1.9G Sep 30 15:31 hisat2_index.5.ht2l
-rw-r--r--. 1 sagnik domain users  2.1G Sep 30 15:31 hisat2_index.6.ht2l
-rw-r--r--. 1 sagnik domain users    12 Sep 30 14:17 hisat2_index.7.ht2l
-rw-r--r--. 1 sagnik domain users    12 Sep 30 14:17 hisat2_index.8.ht2l
-rwxrwxrwx. 1 sagnik domain users  4.6G Sep  7 14:59 Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna.toplevel.fa
-rw-r--r--. 1 sagnik domain users   787 Oct 27 16:12 Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna.toplevel.fa.bed
-rwxrwxrwx. 1 sagnik domain users   281 Dec  2 16:36 Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna.toplevel.fa.fai
-rwxrwxrwx. 1 sagnik domain users   138 Dec  2 10:48 Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna.toplevel.fa.genome
-rwxrwxrwx. 1 sagnik domain users  1.3G Sep 10 16:07 Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna.toplevel.fa.gz
-rw-r--r--. 1 sagnik domain users   55K Sep 30 16:26 Log.out
-rw-------. 1 sagnik domain users  7.1K Sep 30 16:26 nohup.out
drwxr-xr-x. 2 sagnik domain users  4.0K Sep 30 16:26 star_index
-rw-r--r--. 1 sagnik domain users  178M Dec  6 05:18 T1_0_R1.consolidated.fasta

The command I am using to run bowtie is <bowtie -f bowtie1_index T1_0_R1.consolidated.fasta alignment> which leads to the following error.

Could not locate a Bowtie index corresponding to basename "bowtie1_index"
Command: bowtie-align --wrapper basic-0 -f bowtie1_index T1_0_R1.consolidated.fasta alignment 

When I issue the command <bowtie-inspect -s bowtie1_index>, I get the following result:

Colorspace	0
SA-Sample	1 in 32
FTab-Chars	10
Sequence-1	chr1H dna:chromosome chromosome:Hv_IBSC_PGSB_v2:chr1H:1:558535432:1 REF	558535432
Sequence-2	Pt dna:chromosome chromosome:Hv_IBSC_PGSB_v2:Pt:1:115974:1 REF	115974
Sequence-3	chr2H dna:chromosome chromosome:Hv_IBSC_PGSB_v2:chr2H:1:768075024:1 REF	768075024
Sequence-4	chr3H dna:chromosome chromosome:Hv_IBSC_PGSB_v2:chr3H:1:699711114:1 REF	699711114
Sequence-5	chr4H dna:chromosome chromosome:Hv_IBSC_PGSB_v2:chr4H:1:647060158:1 REF	647060158
Sequence-6	chr5H dna:chromosome chromosome:Hv_IBSC_PGSB_v2:chr5H:1:670030160:1 REF	670030160
Sequence-7	chr6H dna:chromosome chromosome:Hv_IBSC_PGSB_v2:chr6H:1:583380513:1 REF	583380513
Sequence-8	chr7H dna:chromosome chromosome:Hv_IBSC_PGSB_v2:chr7H:1:657224000:1 REF	657224000
Sequence-9	chrUn dna:chromosome chromosome:Hv_IBSC_PGSB_v2:chrUn:1:249774706:1 REF	249774706

I am not quite sure what I am doing wrong here.

**Comment by ndaniel** [comment]
Try to add `--large-index`, that is something like this in your case:
```
bowtie --large-index -f bowtie1_index T1_0_R1.consolidated.fasta alignment
```

**Comment by sagnikbanerjee15** [comment]
Thanks it worked!!!

**Comment by BenLangmead** [comment]
Yeah, the `bowtie2` wrapper script is smart enough to detect this, but not the `bowtie` wrapper.  We will likely add this in an upcoming release.

**Comment by ch4rr0** [comment]
A fix for this issue was included as part of our most recent release.
