### ISSUE TITLE
bowtie mapping with fasta input - segmentation fault.

### ISSUE THREAD

**Issue by mortunco** [BenLangmead/bowtie#86]
Hi,

I get segmentation fault when I try to map my reads in fasta format to hg19 genome. Interestingly, I dont get this error when I try to map truncated version of this big fasta files.

This is the segmentation fault that I got when I try to map my fasta file.
```
INFO: Command: /home/tmorova/anaconda2/bin/bowtie-align-s --wrapper basic-0 -v 3 --best --strata -m 1 -t -S --no-unal -p 1 /home/tmorova/tools/bowtie_index/hg19 -f leftonly.extended.DHT.fa.gz leftonly.extended.DHT.sam
Time loading forward index: 00:00:01
Time loading mirror index: 00:00:00
/var/spool/slurm/d/job826138/slurm_script: line 10: 388704 Segmentation fault      bowtie --verbose -v 3 --best --strata -m 1 -t -S --no-unal -p 1 /home/tmorova/tools/bowtie_index/hg19 -f leftonly.extended.DHT.fa.gz leftonly.extended.DHT.sam
mapping done
```

However, when I ran truncated version of the input fasta file (obtained from head -n 100000 leftonly.extended.DHT.fa > deneme.fa )

This is my attempt after I try truncated version of this file.
```
INFO: Command: /home/tmorova/anaconda2/bin/bowtie-align-s --wrapper basic-0 -v 3 --best --strata -m 1 -X 2000 -t -S --no-unal -p 1 /home/tmorova/tools/bowtie_index/hg19 -f deneme.fa.gz leftonly.extended.DHT.sam
Time loading forward index: 00:00:01
Time loading mirror index: 00:00:00
End-to-end 2/3-mismatch full-index search: 00:00:04
# reads processed: 50000
# reads with at least one reported alignment: 50000 (100.00%)
# reads that failed to align: 0 (0.00%)
Reported 50000 alignments
```

It finishes successfully. The memory is not the issue here because I even tried to start the run with 1 core and 500 gb memory. But this segmentation fault remained. Have you ever experienced such a problem ? I googled the problem and could not find similar problems. 

This is the header of the slurm job script that I ran the code. as is it is seen that 500 gb ram allocation does not change this error.
```
This is my latest submission script's specifications
#!/bin/bash
#SBATCH --job-name=star.pbs
#SBATCH --time=06:00:00
#SBATCH --mem-per-cpu=500G
#SBATCH --cpus-per-task=1
#SBATCH --export=all
#SBATCH -p big-mem
```

Bowtie version
```
/home/tmorova/anaconda2/bin/bowtie-align-s version 1.2.2
64-bit
Built on travis-job-f8206593-070a-4409-b40d-8b009fcbb635
Thu Jan 25 20:34:01 UTC 2018
Compiler: gcc version 4.8.5 (GCC)
Options: -O3 -m64 -I/home/tmorova/anaconda2/include -L/home/tmorova/anaconda2/lib -Wl,--hash-style=both -DWITH_TBB -DPOPCNT_CAPABILITY
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

```
I appreciate any kind of guidance to solve this problem.

Best regards,

T.

**Comment by ch4rr0** [comment]
We most likely addressed this issue in a prior release. If you've found that the issue still exits in our most recent release, please feel free to reopen this issue.
