### ISSUE TITLE
bowtie fails to build on Debian testing/gcc-8

### ISSUE THREAD

**Issue by mestia** [BenLangmead/bowtie#87]
Bowtie fails to build on recent linux systems with gcc-8:
Here is the build log:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/bowtie.html
Any hint what might be wrong there?

**Comment by ch4rr0** [comment]
You're not doing anything wrong. It's an error that our compilers have-until-now failed to catch. 

Here's the error.
```
ebwt.h:865:44: error: cannot convert 'TIndexOffU* const' {aka 'long unsigned int* const'} to 'uint32_t*' {aka 'unsigned int*'} in return
  uint32_t*   isa() const          { return _isa; } /* check */
```

If you're looking to build bowtie from source I can commit a fix to the master branch that resolves this.

**Comment by mestia** [comment]
Yes, please provide a patch or reference to a commit fixing the issue. That will be very helpful.

**Comment by ch4rr0** [comment]
https://github.com/BenLangmead/bowtie/commit/58c6ac97b1938909881877ef83167f5eff0e8ab1

**Comment by mestia** [comment]
Awesome! this fixes the build issue. Thank you.
