### ISSUE TITLE
Extremely low mapping rate using D. melanogaster, Flybase, r5.22 genome index

### ISSUE THREAD

**Issue by ruochenj** [BenLangmead/bowtie#91]
Please first excuse me since I am quite new to RNA sequence mapping.

I tried to use bowtie (1.2.2) and  D. melanogaster, Flybase, r5.22 genome index (Retrieved from pre-build index from http://bowtie-bio.sourceforge.net/manual.shtml) to map a fastq file and the results are:

./bowtie --strata --best -n 1 -l 25 -k 1 -m 1 d_melanogaster_fb5_22 RNA_seq_data/fastq/SRR1039765.fastq

# reads processed: 46833204
# reads with at least one reported alignment: 140110 (0.30%)
# reads that failed to align: 46586833 (99.47%)
# reads with alignments suppressed due to -m: 106261 (0.23%)
Reported 140110 alignments

Then I try to blast the first 40 sequences using Blast on NCBI.

For those sequences that have been identified as mRNA sequence using Blast, I try to map them using the D. melanogaster genome index and it says bowtie fails to map them.

example sequences:

sequence | class | description using Blast on NCBI

NACATCGCATGTCGAGGATCTGCAGTACGTAATTAACTTC | mRNA | Drosophila melanogaster maheshvara (mahe), transcript variant C, mRNA

NGTGGTTCCGAGAAGCTCCTGGCTCATCCCACCCATCGTA | mRNA | Drosophila melanogaster alcohol dehydrogenase, transcript variant E (Adh), mRNA

ACCGTGGTTCTTAATTACCACGTCACAGGCAAGACAGGGA | mRNA | Drosophila melanogaster uncharacterized protein, transcript variant E (CG11596), mRNA

Mapping using Bowtie:

(base) id-55-171:bowtie-1.2.2-macos-x86_64 andy$ ./bowtie d_melanogaster_fb5_22 -c NACATCGCATGTCGAGGATCTGCAGTACGTAATTAACTTC
# reads processed: 1
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 1 (100.00%)
No alignments

(base) id-55-171:bowtie-1.2.2-macos-x86_64 andy$ ./bowtie d_melanogaster_fb5_22 -c NGTGGTTCCGAGAAGCTCCTGGCTCATCCCACCCATCGTA
# reads processed: 1
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 1 (100.00%)
No alignments

(base) id-55-171:bowtie-1.2.2-macos-x86_64 andy$ ./bowtie d_melanogaster_fb5_22 -c ACCGTGGTTCTTAATTACCACGTCACAGGCAAGACAGGGA
# reads processed: 1
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 1 (100.00%)
No alignments

May I have some advice on why this happens?

Best,
Andy

**Comment by BenLangmead** [comment]
Low mapping rates are based diagnosed on the user side.  Common reasons are: (a) mismatch between indexed ref genome and donor genome, (b) "true" alignments are non-contiguous, and therefore require e.g. spliced alignment -- this might be the case here, (c) poor quality data.  But this issue area is focused on software issues rather than usage.
