### ISSUE TITLE
bowtie with recent SeqAn

### ISSUE THREAD

**Issue by mestia** [BenLangmead/bowtie#93]
Could you please consider applying patches from Debian[0] to make bowtie work with the latest SeqAn-1.4? This way embedded version of SeqAn-1.1 can be dropped.

Thank you, 
Alex

[0] https://salsa.debian.org/med-team/bowtie/tree/master/debian/patches

**Comment by junaruga** [comment]
@mestia The Seqan dependency was dropped in the bowtie latest version 1.3.0, if you upgrade it, maybe you can remove the patch related to SeqAn.

**Comment by junaruga** [comment]
@mestia Possibly you need a patch to build bowtie on Debian. You can see https://github.com/BenLangmead/bowtie/issues/114#issuecomment-664808008 .

**Comment by ch4rr0** [comment]
We replaced SeqAn with in-house code in our previous release: v1.3.0.
