### ISSUE TITLE
Axolotl genome index building with Bowtie 1.2.3

### ISSUE THREAD

**Issue by Gil-marquez** [BenLangmead/bowtie#96]
I'm trying to bowtie-build the axolotl genome with Bowtie 1.2.3, but the run never finishes even when using the --large-index option. I'm using Bowtie instead of bowtie 2 (which succesfully creates the index) because I have small reads (<=50 bp SE). 
The axolotl genome is about 32 Gb, is there any other way I can make a single index of this genome with Bowtie 1 and avoid creating multiple indexes after fractioning the sequence?

Has any one succesfully completed the bowtie-build for this genome?

Thanks in advance!

Thanks

**Comment by Riptides** [comment]
While I haven't tested personally, the changelog states that Bowtie v1.2.3 can now use Bowtie2 indexes, which should solve your problem.

**Comment by ch4rr0** [comment]
I know this issue is over 2 years old now, but I believe that the fix for [#124](https://github.com/BenLangmead/bowtie/issues/124) should also resolve this one.

**Comment by ch4rr0** [comment]
The change which seeks to address this issue has been released as part of v1.3.1. Feel free to reopen this tracker if the issue persists.
